In [28]:
import numpy as np
a = np.array([1,2,3],dtype='int32')
print(a)






[1 2 3]


In [13]:
b = np.array([[1.67,4.78,9.45],[2.34,4.56,9.98],[2.34,4.56,9.98]])
print(b)



[[1.67 4.78 9.45]
 [2.34 4.56 9.98]
 [2.34 4.56 9.98]]


In [19]:
#Get dimention
a.ndim



1

In [23]:

#Get Shape
a.shape

(3,)

In [22]:
#Get shape
b.shape


(3, 3)

In [26]:
#Get the Type
a.dtype

dtype('int16')

In [30]:
#Get Size
a.itemsize

4

In [33]:
#Get Total size
a.size * a.itemsize

12

In [35]:
a.nbytes

12

In [38]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [40]:
a.shape

(2, 7)

In [42]:
#Get a specific element[r,c]
a[1,5]

13

In [44]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [50]:
#Getring a little more fency [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [54]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)


[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [56]:
print(b)

[[1.67 4.78 9.45]
 [2.34 4.56 9.98]
 [2.34 4.56 9.98]]


In [ ]:
#Get a specifc eleme