In [2]:
print("This is python")

This is python


In [3]:
name = ['John','Alex','Sam','Matt']

for i in name:
    print(i)

John
Alex
Sam
Matt


In [4]:
name = {1,2,3,4,5,6}
name

{1, 2, 3, 4, 5, 6}

In [5]:
for i in name:
    print(i)

1
2
3
4
5
6


In [6]:
for i in name:
    if i%2!=0:
        print(i)

1
3
5


In [7]:
type(name)

set

In [8]:
std_name =  ['John','Alex','Sam','Matt']
type(std_name)

list

In [9]:
a = []

for i in range(1,10):
    a.append(i)

print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
a = True
type(a)

bool

In [11]:
c = 'Hello word'
type(c)

str

In [12]:
com = 4+6j
type(com)

complex

In [13]:
# Arithmetic operation

num = 2**3
print(num)

8


In [14]:
a =10
b=20
a+b

30

In [15]:
a-b

-10

In [16]:
a*b

200

In [17]:
a**b

100000000000000000000

In [18]:
a/b

0.5

In [19]:
a%b

10

In [20]:
a^b

30

In [21]:
a&b

0

In [22]:
#Relational operators

In [23]:
if a==b:
    print("Equal")
elif a>b:
    print("a is big")
else:
  print("b is big")

b is big


In [24]:
a!=b

True

In [25]:
a==b

False

In [26]:
a>b

False

In [27]:
a<b

True

In [28]:
#Logical operator

In [29]:
a = True
b = False
a&b

False

In [30]:
a|b

True

In [31]:
b&a

False

In [32]:
b|a

True

In [33]:
a&a

True

In [34]:
b&b

False

In [35]:
a|a

True

In [36]:
b|b

False

In [37]:
b or a

True

In [38]:
line = """I am going to Dhaka Tomorrow"""
line

'I am going to Dhaka Tomorrow'

In [39]:
type(line)

str

In [40]:
line_1 = "I am going to School"
line_1[0]

'I'

In [41]:
line_1[-1]

'l'

In [42]:
line_1[-2]

'o'

In [43]:
line_1[-3]

'o'

In [44]:
line_1[5:12] # 12 is exclusive and 5 is inclusive like [a,b)

'going t'

In [45]:
len(line_1)

20

In [46]:
len(line)

28

In [47]:
line.upper()

'I AM GOING TO DHAKA TOMORROW'

In [48]:
line_1.lower()

'i am going to school'

In [49]:
line.title()

'I Am Going To Dhaka Tomorrow'

In [50]:
#Tuple , List , Dict , Set

In [51]:
tup =(1,'a',True,'Kowshik','Oii',23.89)
tup

(1, 'a', True, 'Kowshik', 'Oii', 23.89)

In [52]:
tup[0]

1

In [53]:
tup[-1]

23.89

In [54]:
tup[:-1]

(1, 'a', True, 'Kowshik', 'Oii')

In [55]:
tup[0:-1]

(1, 'a', True, 'Kowshik', 'Oii')

In [56]:
tup[1:4]

('a', True, 'Kowshik')

In [57]:
tup[0] =  3 # Tuples are im-mutable

TypeError: 'tuple' object does not support item assignment

In [58]:
#List are mutable

In [59]:
lst = [1,"kowshik",'oi']
lst

[1, 'kowshik', 'oi']

In [60]:
lst[-2]

'kowshik'

In [61]:
lst[0] = 'kos'
lst

['kos', 'kowshik', 'oi']

In [62]:
lst[1:5]

['kowshik', 'oi']

In [63]:
lst.append("sowrds")
lst

['kos', 'kowshik', 'oi', 'sowrds']

In [64]:
lst.append([1,2,3,4])
lst

['kos', 'kowshik', 'oi', 'sowrds', [1, 2, 3, 4]]

In [65]:
lst.pop()

[1, 2, 3, 4]

In [66]:
lst

['kos', 'kowshik', 'oi', 'sowrds']

In [67]:
lst.pop()

'sowrds'

In [68]:
lst

['kos', 'kowshik', 'oi']

In [69]:
#Dictonary are mutable

In [70]:
dc={1:"Orange", 2:"Mango" , 3:"Apple" , 4:"Pineapple"}
dc

{1: 'Orange', 2: 'Mango', 3: 'Apple', 4: 'Pineapple'}

In [71]:
dc.keys()

dict_keys([1, 2, 3, 4])

In [72]:
dc.values()

dict_values(['Orange', 'Mango', 'Apple', 'Pineapple'])

In [73]:
dc[2] = "Guava"
dc

{1: 'Orange', 2: 'Guava', 3: 'Apple', 4: 'Pineapple'}

In [74]:
#set are un-indexed  

In [75]:
s ={1,"a",3.56}
s

{1, 3.56, 'a'}

In [76]:
s ={1,"a", 3.56 , 1 , "a" , 1 , 1 }
s

{1, 3.56, 'a'}

In [77]:
s.add("Hello")
s

{1, 3.56, 'Hello', 'a'}

In [78]:
s.update(['kowshik0','213123', 'asdad'])
s

{1, '213123', 3.56, 'Hello', 'a', 'asdad', 'kowshik0'}

In [79]:
#if statement

In [80]:
a = 10 
b = 20

if b>a:
    print("b>a")
else:
    print("a>b")

b>a


In [81]:
tup1 = ('a','b','c')
if 'a' in tup1:
    print("a is present")

a is present


In [82]:
if 's' in tup1:
    print("present")

In [83]:
l1 = [1,2,3,4,56]
if l1[0]==1:
    l1[0] =100;
l1

[100, 2, 3, 4, 56]

In [84]:
d1 = {"mango":10 , "apple":20 , "banana":30}

if d1["mango"]==10:
    d1["mango"]+=10;

d1

{'mango': 20, 'apple': 20, 'banana': 30}

In [85]:
i = 1

while(i<=10):
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10


In [86]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [87]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [88]:
l1 = [1,2,3,4]

i = 0

while i<len(l1):
    print(l1[i])
    i+=1;

1
2
3
4


In [89]:
l1 = ['red' , 'blue' , 'green']
for i in l1:
    print(i)

red
blue
green


In [90]:
item = ['chart' , 'book' , 'plea']


for i in l1:
    for j in item:
        print(i,j)

red chart
red book
red plea
blue chart
blue book
blue plea
green chart
green book
green plea


In [91]:
#Function

In [92]:
def hello():
    print("Hello")
    

hello()

Hello


In [93]:
def add(a):
    return a+10

add(4)


14

In [94]:
add(1123)

1133

In [95]:
add(100)

110

In [96]:
def odd_even(x):
    if x%2!=0:
        return "odd"
    else:
        return "even"

    
odd_even(10)

'even'

In [97]:
odd_even(3)

'odd'

In [98]:
class Phone:
    def make_call(self):
        print("Making a phone call")
    def play_game(self):
        print("Plying game")
    

In [99]:
p1 = Phone()

In [100]:
p1.make_call()

Making a phone call


In [101]:
p1.play_game()

Plying game


In [102]:
class Phone:
    def add_color(self,color):
        seft.color = color
        
    def add_cost(self,cost):
        self.cost=cost
        
    def show_color(self):
        return self.color
    
    def show_cost(self):
        return self.cost
    
    def make_call(self):
        print("calling")
        
    def play_game(self):
        print("gaming")

In [103]:
p2 = Phone()


In [104]:
p2.add_color("red")

NameError: name 'seft' is not defined

In [105]:
p2.add_cost(100)

In [106]:
p2.show_color()

AttributeError: 'Phone' object has no attribute 'color'

In [107]:
p2.show_cost()

100

In [108]:
import numpy as np

In [109]:
ar=np.array([1,2,3,4,5,6,7])

In [110]:
ar

array([1, 2, 3, 4, 5, 6, 7])

In [111]:
type(ar)

numpy.ndarray

In [112]:
br = np.array([[1,2,3],[1,2,6]])
br

array([[1, 2, 3],
       [1, 2, 6]])

In [113]:
type(br)

numpy.ndarray

In [114]:
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [115]:
n2 = np.zeros((2,2))
n2

array([[0., 0.],
       [0., 0.]])

In [116]:
n1 = np.zeros((6,6))
n1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [117]:
n3 = np.full((2,2),10)
n3

array([[10, 10],
       [10, 10]])

In [118]:
n4 = np.full((6,6),7)
n4

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [119]:
n1 = np.arange(1,10)
n1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
n1 = np.arange(1,100,5) #5 kore increment hobe
n1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [121]:
n1 = np.arange(10,1,-2)
n1

array([10,  8,  6,  4,  2])

In [122]:
n1 = np.random.randint(1,100,10)
n1

array([60, 99, 54, 92, 16, 46, 33, 94, 41, 14])

In [123]:
n1 = np.array([[1,2,3,4],[1,2,3,4]])
n1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [124]:
n1.shape

(2, 4)

In [125]:
n1.shape=(4,2)

In [126]:
n1

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [127]:
n1.shape

(4, 2)

In [128]:
n1 = np.array([1,2])
n2 = np.array([5,6])
np.sum(n1+n2)

14

In [129]:
np.sum([n1,n2],axis=0)

array([6, 8])

In [130]:
np.sum([n1,n2],axis=1)

array([ 3, 11])

In [131]:
n1 = np.array([10,20,30])
n2 = np.array([30,40,50])

In [132]:
np.vstack([n1,n2])

array([[10, 20, 30],
       [30, 40, 50]])

In [133]:
np.hstack([n1,n2])

array([10, 20, 30, 30, 40, 50])

In [134]:
np.column_stack([n1,n2])

array([[10, 30],
       [20, 40],
       [30, 50]])

In [135]:
import pandas as pd

In [136]:
s1=pd.Series([1,2,3,4,5,6])
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [137]:
type(s1)

pandas.core.series.Series

In [138]:
s1=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [139]:
s1 = pd.Series({'a':10,'b':20,'c':30})
s1

a    10
b    20
c    30
dtype: int64

In [142]:
student = {"Student_Name":['Bob','Sam','Anee'] , "Student_Marks":[12,23,45]}

In [146]:
s1 = pd.DataFrame(student)
s1

Student_Name  Student_Marks
0          Bob             12
1          Sam             23
2         Anee             45

In [147]:
s1.head()

Student_Name  Student_Marks
0          Bob             12
1          Sam             23
2         Anee             45

In [148]:
iris = pd.read_csv('Cardio.csv')

In [149]:
iris.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [150]:
iris.tail()

Product  Age Gender  Education MaritalStatus  Usage  Fitness  Income  \
175   TM798   40   Male         21        Single      6        5   83416   
176   TM798   42   Male         18        Single      5        4   89641   
177   TM798   45   Male         16        Single      5        5   90886   
178   TM798   47   Male         18     Partnered      4        5  104581   
179   TM798   48   Male         18     Partnered      4        5   95508   

     Miles  
175    200  
176    200  
177    160  
178    120  
179    180

In [151]:
iris.head(n=10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [152]:
iris.tail(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [153]:
iris.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [156]:
iris.iloc[0:3,0:2] # left side row and right side column

Product  Age
0   TM195   18
1   TM195   19
2   TM195   19

In [157]:
iris.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [160]:
iris2 = iris.iloc[5:10,[1,3]]

In [161]:
iris2

Age  Education
5   20         14
6   21         14
7   21         13
8   21         15
9   21         15

In [162]:
iris.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47

In [163]:
iris3 = iris.loc[10:21,("Age","Education","Income")]


In [164]:
iris3

Age  Education  Income
10   22         14   36384
11   22         14   35247
12   22         16   36384
13   22         14   35247
14   23         16   38658
15   23         16   40932
16   23         14   34110
17   23         16   39795
18   23         16   38658
19   23         15   34110
20   23         14   38658
21   23         16   40932

In [180]:
iris[iris['Age']>18]

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
1     TM195   19    Male         15        Single      2        3   31836   
2     TM195   19  Female         14     Partnered      4        3   30699   
3     TM195   19    Male         12        Single      3        3   32973   
4     TM195   20    Male         13     Partnered      4        2   35247   
5     TM195   20  Female         14     Partnered      3        3   32973   
..      ...  ...     ...        ...           ...    ...      ...     ...   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
1       75  
2       66  
3       85  
4       47  
5       66  
..     ...  
175    200  
176    200  
177    160  
178    120  
179    180  

[179 rows x 9 columns]

In [185]:
iris_final = iris[(iris['Age']>=25) & (iris['MaritalStatus']=='Single')]

In [186]:
iris_final

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
31    TM195   25    Male         16        Single      3        4   40932   
33    TM195   25    Male         16        Single      3        3   43206   
38    TM195   26  Female         16        Single      3        3   36384   
40    TM195   26    Male         16        Single      3        3   50028   
42    TM195   27    Male         16        Single      4        3   54576   
46    TM195   28    Male         14        Single      3        3   52302   
48    TM195   28    Male         14        Single      4        3   54576   
54    TM195   30    Male         14        Single      3        3   54576   
56    TM195   31  Female         14        Single      2        2   45480   
57    TM195   32  Female         14        Single      3        4   46617   
59    TM195   33  Female         16        Single      2        2   55713   
61    TM195   34    Male         16        Single      4        5   51165   
62    TM195   34  Female         16        Single      2        2   52302   
65    TM195   35  Female         18        Single      3        3   67083   
66    TM195   36    Male         12        Single      4        3   44343   
70    TM195   38    Male         14        Single      2        3   52302   
76    TM195   44  Female         16        Single      3        4   57987   
98    TM498   25  Female         14        Single      3        4   43206   
101   TM498   25    Male         14        Single      3        3   45480   
102   TM498   25  Female         14        Single      2        3   43206   
106   TM498   25  Female         14        Single      2        2   45480   
107   TM498   25    Male         14        Single      4        3   48891   
109   TM498   26  Female         16        Single      4        4   50028   
110   TM498   26    Male         16        Single      4        3   51165   
111   TM498   27    Male         14        Single      4        2   45480   
113   TM498   30  Female         14        Single      3        3   57987   
114   TM498   30  Female         13        Single      4        3   46617   
117   TM498   31  Female         18        Single      2        1   65220   
118   TM498   32    Male         16        Single      4        3   60261   
124   TM498   33  Female         18        Single      3        4   47754   
127   TM498   34    Male         15        Single      3        3   67083   
130   TM498   35  Female         16        Single      3        2   50028   
136   TM498   40  Female         16        Single      3        3   57987   
157   TM798   26  Female         21        Single      4        3   69721   
160   TM798   27    Male         18        Single      4        3   88396   
164   TM798   28    Male         18        Single      6        5   88396   
165   TM798   29    Male         18        Single      5        5   52290   
172   TM798   34    Male         16        Single      5        5   92131   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   

     Miles  
31     113  
33      85  
38      66  
40      85  
42      85  
46     103  
48     113  
54      85  
56      47  
57     113  
59      38  
61     169  
62      66  
65      85  
66      94  
70      56  
76      75  
98     127  
101     95  
102     64  
106     42  
107    127  
109    127  
110    106  
111     53  
113     74  
114    106  
117     21  
118    127  
124     74  
127     85  
130     64  
136     85  
157    100  
160    100  
164    150  
165    180  
172    150  
175    200  
176    200  
177    160

In [190]:
iris_final.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
31   TM195   25    Male         16        Single      3        4   40932   
33   TM195   25    Male         16        Single      3        3   43206   
38   TM195   26  Female         16        Single      3        3   36384   
40   TM195   26    Male         16        Single      3        3   50028   
42   TM195   27    Male         16        Single      4        3   54576   

    Miles  
31    113  
33     85  
38     66  
40     85  
42     85

In [196]:
iris4 = iris[(iris['Age']>=25) & (iris['MaritalStatus']=='Partnered') & (iris['Income']>=40000)]

In [198]:
iris4.head()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
27   TM195   25  Female         14     Partnered      3        3   48891   
28   TM195   25    Male         14     Partnered      2        3   45480   
29   TM195   25  Female         14     Partnered      2        2   53439   
32   TM195   25  Female         16     Partnered      2        2   40932   
34   TM195   26  Female         14     Partnered      3        4   44343   

    Miles  
27     75  
28     56  
29     47  
32     47  
34    113

In [203]:
iris4.describe(include='all')

Product        Age Gender  Education MaritalStatus      Usage  \
count       83  83.000000     83  83.000000            83  83.000000   
unique       3        NaN      2        NaN             1        NaN   
top      TM195        NaN   Male        NaN     Partnered        NaN   
freq        34        NaN     49        NaN            83        NaN   
mean       NaN  31.939759    NaN  15.903614           NaN   3.518072   
std        NaN   6.761349    NaN   1.486643           NaN   1.233293   
min        NaN  25.000000    NaN  13.000000           NaN   2.000000   
25%        NaN  26.000000    NaN  15.000000           NaN   3.000000   
50%        NaN  30.000000    NaN  16.000000           NaN   3.000000   
75%        NaN  35.000000    NaN  16.000000           NaN   4.000000   
max        NaN  50.000000    NaN  21.000000           NaN   7.000000   

          Fitness         Income       Miles  
count   83.000000      83.000000   83.000000  
unique        NaN            NaN         NaN  
top           NaN            NaN         NaN  
freq          NaN            NaN         NaN  
mean     3.397590   60731.349398  110.325301  
std      0.949194   16587.454793   62.278898  
min      2.000000   40932.000000   38.000000  
25%      3.000000   50028.000000   66.000000  
50%      3.000000   53439.000000   94.000000  
75%      4.000000   64775.000000  136.500000  
max      5.000000  104581.000000  360.000000