In [1]:
distance = [23,34,56]
speed = [3,12,8]

time = distance/speed
print(time)


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [2]:
import numpy as np

dist = np.array(distance)
spd = np.array(speed)
print(dist)
print(spd)
tm = dist/spd
print(tm)


[23 34 56]
[ 3 12  8]
[7.66666667 2.83333333 7.        ]


In [3]:
a = [1,2,3,4]
b = [10,20,30,40]
print(a+b) # Concatanations 
#print(a+5)

[1, 2, 3, 4, 10, 20, 30, 40]


In [4]:
f = np.array((1,2,3,4))
g = np.array((10,20,30,40))
print(f.dtype)
print(f)
print(g)
print(f+g)
print(f+5)

f**2
g**3

int32
[1 2 3 4]
[10 20 30 40]
[11 22 33 44]
[6 7 8 9]


array([ 1000,  8000, 27000, 64000], dtype=int32)

In [5]:
c = np.arange(10)
print(c)

anarray = np.arange(5,55,5)
print(anarray)

kos = np.arange(20,1,-2)
print(kos)

kos1 = np.linspace(1,100,30)
print(kos1)

[0 1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45 50]
[20 18 16 14 12 10  8  6  4  2]
[  1.           4.4137931    7.82758621  11.24137931  14.65517241
  18.06896552  21.48275862  24.89655172  28.31034483  31.72413793
  35.13793103  38.55172414  41.96551724  45.37931034  48.79310345
  52.20689655  55.62068966  59.03448276  62.44827586  65.86206897
  69.27586207  72.68965517  76.10344828  79.51724138  82.93103448
  86.34482759  89.75862069  93.17241379  96.5862069  100.        ]


In [6]:
data = np.array((434,3423,2323,2454,56,56,23,23,4,5,2,3,12,12,234,234,234,234,345,345,345,345,12,53))
data
data = data.reshape(8,3)
data2 = data.reshape(2,2,2,3) # 4 dimention
data2

even_data = (data % 2 ==0 )
print(even_data)
data[even_data]

[[ True False False]
 [ True  True  True]
 [False False  True]
 [False  True False]
 [ True  True  True]
 [ True  True  True]
 [False False False]
 [False  True False]]


array([ 434, 2454,   56,   56,    4,    2,   12,   12,  234,  234,  234,
        234,   12])

In [7]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,4))+6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [9]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.ones((2,3))+4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [11]:
np.ones((3,4,5))+3

array([[[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]],

       [[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [14]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])